-- 코드를 입력하세요
SELECT FP.PRODUCT_ID AS PRODUCT_ID, FP.PRODUCT_NAME, (FP.PRICE * SUM(FO.AMOUNT)) AS TOTAL_SALES
FROM FOOD_ORDER AS FO JOIN  FOOD_PRODUCT FP ON FO.PRODUCT_ID = FP.PRODUCT_ID
WHERE FO.PRODUCE_DATE BETWEEN "2022-05-01" AND "2022-05-31"
GROUP BY FP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID